# Generated by Django 4.2.16 on 2024-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=100, verbose_name='Computer name')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event type')),
                ('application', models.CharField(max_length=100, verbose_name='Application')),
                ('window_title', models.CharField(max_length=100, verbose_name='Window title')),
                ('content', models.CharField(max_length=255, verbose_name='Content')),
                ('screenshot', models.ImageField(upload_to='screenshot/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
